import csv

# Methodology:
# 1. AAC Super Core: High-priority functional words (pronouns, requests, social).
# 2. High Frequency: Top words from corpus, filtered for utility (concrete over abstract).

aac_super_core = [
    # Social
    ("tak", "social", 1),
    ("nie", "social", 1),
    ("cześć", "social", 1),
    ("dziękuję", "social", 1),
    ("proszę", "social", 1),
    ("przepraszam", "social", 1),
    ("pa", "social", 1),
    ("dobranoc", "social", 2),
    ("dzień dobry", "social", 2),
    # Pronouns
    ("ja", "pronoun", 1),
    ("ty", "pronoun", 1),
    ("to", "pronoun", 1),
    ("on", "pronoun", 1),
    ("ona", "pronoun", 1),
    ("my", "pronoun", 2),
    ("wy", "pronoun", 2),
    ("oni", "pronoun", 2),
    ("one", "pronoun", 2),
    ("moje", "pronoun", 1),
    ("twoje", "pronoun", 1),
    ("się", "pronoun", 1),
    ("swoje", "pronoun", 2),
    ("coś", "pronoun", 1),
    ("ktoś", "pronoun", 1),
    ("wszyscy", "pronoun", 2),
    ("wszystko", "pronoun", 2),
    ("nic", "pronoun", 2),
    ("nikt", "pronoun", 2),
    # Questions
    ("co", "question", 1),
    ("kto", "question", 1),
    ("gdzie", "question", 1),
    ("kiedy", "question", 1),
    ("dlaczego", "question", 1),
    ("jak", "question", 1),
    ("który", "question", 2),
    ("czemu", "question", 2),
    # Verbs (Infinitives usually, but AAC often uses roots. Listed as base forms)
    ("chcieć", "verb", 1),
    ("dać", "verb", 1),
    ("mieć", "verb", 1),
    ("być", "verb", 1),
    ("iść", "verb", 1),
    ("lubić", "verb", 1),
    ("robić", "verb", 1),
    ("jeść", "verb", 1),
    ("pić", "verb", 1),
    ("spać", "verb", 1),
    ("widzieć", "verb", 1),
    ("słyszeć", "verb", 1),
    ("mówić", "verb", 1),
    ("pomóc", "verb", 1),
    ("czekać", "verb", 1),
    ("bawić się", "verb", 1),
    ("myć", "verb", 1),
    ("otwierać", "verb", 2),
    ("zamykać", "verb", 2),
    ("szukać", "verb", 2),
    ("znaleźć", "verb", 2),
    ("przyjść", "verb", 2),
    ("wyjść", "verb", 2),
    ("brać", "verb", 2),
    ("wziąć", "verb", 2),
    ("dostać", "verb", 2),
    ("kupić", "verb", 2),
    ("musieć", "verb", 1),
    ("móc", "verb", 1),
    ("umieć", "verb", 1),
    ("wiedzieć", "verb", 1),
    ("rozumieć", "verb", 2),
    ("pamiętać", "verb", 2),
    ("zobaczyć", "verb", 1),
    ("patrzeć", "verb", 1),
    ("skończyć", "verb", 1),
    ("zacząć", "verb", 2),
    ("jechać", "verb", 2),
    ("stać", "verb", 2),
    ("siedzieć", "verb", 2),
    ("leżeć", "verb", 2),
    ("pracować", "verb", 2),
    ("uczyć się", "verb", 2),
    ("pisać", "verb", 2),
    ("czytać", "verb", 2),
    ("rysować", "verb", 2),
    ("oglądać", "verb", 2),
    ("grać", "verb", 2),
    ("biegać", "verb", 2),
    ("skakać", "verb", 2),
    ("pływać", "verb", 2),
    ("boleć", "verb", 1),
    ("bać się", "verb", 2),
    ("cieszyć się", "verb", 2),
    # Adverbs / Adjectives / Time / Place
    ("jeszcze", "adverb", 1),
    ("już", "adverb", 1),
    ("teraz", "time", 1),
    ("potem", "time", 1),
    ("zaraz", "time", 2),
    ("wczoraj", "time", 2),
    ("jutro", "time", 2),
    ("dzisiaj", "time", 2),
    ("zawsze", "time", 2),
    ("nigdy", "time", 2),
    ("czasami", "time", 2),
    ("długo", "time", 2),
    ("krótko", "time", 2),
    ("tu", "place", 1),
    ("tam", "place", 1),
    ("blisko", "place", 2),
    ("daleko", "place", 2),
    ("góra", "place", 2),
    ("dół", "place", 2),
    ("środek", "place", 2),
    ("dobrze", "adverb", 1),
    ("źle", "adverb", 1),
    ("dużo", "quantity", 1),
    ("mało", "quantity", 1),
    ("więcej", "quantity", 1),
    ("mniej", "quantity", 2),
    ("szybko", "adverb", 2),
    ("wolno", "adverb", 2),
    ("głośno", "adverb", 2),
    ("cicho", "adverb", 2),
    ("fajnie", "adverb", 1),
    ("ładnie", "adverb", 2),
    ("dobry", "adjective", 1),
    ("zły", "adjective", 1),
    ("duży", "adjective", 1),
    ("mały", "adjective", 1),
    ("ciepły", "adjective", 1),
    ("zimny", "adjective", 1),
    ("mokry", "adjective", 2),
    ("suchy", "adjective", 2),
    ("brudny", "adjective", 2),
    ("czysty", "adjective", 2),
    ("głodny", "adjective", 1),
    ("spragniony", "adjective", 2),
    ("zmęczony", "adjective", 2),
    ("chory", "adjective", 2),
    ("smutny", "adjective", 2),
    ("wesoły", "adjective", 2),
    ("nowy", "adjective", 2),
    ("stary", "adjective", 2),
    ("łatwy", "adjective", 2),
    ("trudny", "adjective", 2),
    ("fajny", "adjective", 1),
    ("taki", "adjective", 2),
    ("inny", "adjective", 2),
    ("sam", "adjective", 2),
    ("gotowy", "adjective", 2),
    # Prepositions / Conjunctions
    ("w", "preposition", 1),
    ("na", "preposition", 1),
    ("z", "preposition", 1),
    ("do", "preposition", 1),
    ("o", "preposition", 1),
    ("od", "preposition", 1),
    ("dla", "preposition", 1),
    ("bez", "preposition", 2),
    ("przez", "preposition", 2),
    ("za", "preposition", 2),
    ("pod", "preposition", 2),
    ("nad", "preposition", 2),
    ("u", "preposition", 2),
    ("koło", "preposition", 2),
    ("i", "conjunction", 1),
    ("a", "conjunction", 1),
    ("ale", "conjunction", 1),
    ("lub", "conjunction", 2),
    ("albo", "conjunction", 2),
    ("bo", "conjunction", 1),
    ("że", "conjunction", 1),
    ("żeby", "conjunction", 2),
    ("czy", "conjunction", 1),
    # Essential Nouns (Categories)
    ("mama", "noun", 1),
    ("tata", "noun", 1),
    ("dom", "noun", 1),
    ("szkoła", "noun", 1),
    ("przedszkole", "noun", 2),
    ("praca", "noun", 2),
    ("pan", "noun", 1),
    ("pani", "noun", 1),
    ("dziecko", "noun", 2),
    ("chłopak", "noun", 2),
    ("dziewczyna", "noun", 2),
    ("rodzina", "noun", 2),
    ("woda", "noun", 1),
    ("jedzenie", "noun", 1),
    ("obiad", "noun", 2),
    ("śniadanie", "noun", 2),
    ("kolacja", "noun", 2),
    ("chleb", "noun", 2),
    ("picie", "noun", 1),
    ("sok", "noun", 2),
    ("mleko", "noun", 2),
    ("jabłko", "noun", 2),
    ("ciastko", "noun", 2),
    ("toaleta", "noun", 1),
    ("łazienka", "noun", 2),
    ("pokój", "noun", 2),
    ("łóżko", "noun", 2),
    ("stół", "noun", 2),
    ("krzesło", "noun", 2),
    ("samochód", "noun", 2),
    ("autobus", "noun", 2),
    ("zabawa", "noun", 1),
    ("gra", "noun", 2),
    ("bajka", "noun", 2),
    ("piłka", "noun", 2),
    ("lalka", "noun", 2),
    ("klocki", "noun", 2),
    ("tablet", "noun", 2),
    ("telefon", "noun", 2),
    ("komputer", "noun", 2),
    ("pies", "noun", 2),
    ("kot", "noun", 2),
    ("dzień", "noun", 2),
    ("noc", "noun", 2),
    ("czas", "noun", 2),
    ("rzecz", "noun", 2),
    ("sprawa", "noun", 2),
    ("miejsce", "noun", 2),
    ("problem", "noun", 2),
    ("pomysł", "noun", 2),
]

# Supplementary High Frequency (to reach 500)
# Based on SUBTLEX-PL / Wiktionary frequency but filtered for utility.
supplementary_raw = [
    # Verbs
    "pytać",
    "odpowiadać",
    "zmieniać",
    "czuć",
    "zostać",
    "wracać",
    "spotkać",
    "trzymać",
    "nosić",
    "używać",
    "nazywać",
    "pozwolić",
    "zostawić",
    "prosić",
    "pokazać",
    "wierzyć",
    "kochać",
    "nienawidzić",
    "martwić się",
    "interesować",
    "próbować",
    "sprawdzić",
    "wyglądać",
    "zdarzyć się",
    "udać się",
    "brakować",
    "kosztować",
    "płacić",
    "kupować",
    "sprzedawać",
    "podać",
    "przynieść",
    "zanieść",
    "położyć",
    "postawić",
    "wisieć",
    "upaść",
    "rzucić",
    "złapać",
    "kopnąć",
    "uderzyć",
    "tulić",
    "całować",
    "śmiać się",
    "płakać",
    "krzyczeć",
    "szeptać",
    "śpiewać",
    "tańczyć",
    "rysować",
    "malować",
    "gotować",
    "piec",
    "kroić",
    "sprzątać",
    "prać",
    "prasować",
    "budować",
    "naprawiać",
    "psuć",
    "zgubić",
    "zapomnieć",
    "przypomnieć",
    "wybrać",
    "woleć",
    "potrzebować",
    # Adjectives/Adverbs
    "ważny",
    "możliwy",
    "niemożliwy",
    "prawdziwy",
    "sztuczny",
    "jasny",
    "ciemny",
    "kolorowy",
    "czarny",
    "biały",
    "czerwony",
    "niebieski",
    "zielony",
    "żółty",
    "długi",
    "krótki",
    "wysoki",
    "niski",
    "gruby",
    "chudy",
    "prosty",
    "krzywy",
    "pełny",
    "pusty",
    "otwarty",
    "zamknięty",
    "tani",
    "drogi",
    "bezpieczny",
    "niebezpieczny",
    "wolny",
    "zajęty",
    "spokojny",
    "nerwowy",
    "miły",
    "niemiły",
    "mądry",
    "głupi",
    "piękny",
    "brzydki",
    "gorący",
    "smaczny",
    "słodki",
    "kwaśny",
    "słony",
    "ostry",
    "miękki",
    "twardy",
    "lekki",
    "ciężki",
    "silny",
    "słaby",
    "zdrowy",
    "szczęśliwy",
    "pierwszy",
    "drugi",
    "ostatni",
    "następny",
    "poprzedni",
    # Time
    "tydzień",
    "miesiąc",
    "rok",
    "godzina",
    "minuta",
    "rano",
    "wieczór",
    "południe",
    "poniedziałek",
    "wtorek",
    "środa",
    "czwartek",
    "piątek",
    "sobota",
    "niedziela",
    "zima",
    "lato",
    "wiosna",
    "jesień",
    "święto",
    "urodziny",
    # Nouns - Body
    "głowa",
    "ręka",
    "noga",
    "brzuch",
    "oko",
    "ucho",
    "nos",
    "buzia",
    "włosy",
    "palec",
    "plecy",
    "krew",
    "serce",
    # Nouns - Food
    "woda",
    "herbata",
    "kawa",
    "zupa",
    "mięso",
    "ziemniaki",
    "ryż",
    "makaron",
    "owoc",
    "warzywo",
    "banan",
    "lody",
    "czekolada",
    "cukier",
    "sól",
    # Nouns - Places/Home
    "sklep",
    "ulica",
    "miasto",
    "wieś",
    "ogród",
    "park",
    "plac zabaw",
    "las",
    "kuchnia",
    "salon",
    "drzwi",
    "okno",
    "ściana",
    "podłoga",
    "schody",
    "winda",
    # Nouns - Objects
    "klucz",
    "pieniądze",
    "torba",
    "plecak",
    "zegarek",
    "okulary",
    "ubranie",
    "buty",
    "spodnie",
    "koszulka",
    "czapka",
    "kurtka",
    "papier",
    "długopis",
    "książka",
    "zeszyt",
    "prezent",
    # Nouns - People/Animals
    "kobieta",
    "mężczyzna",
    "człowiek",
    "przyjaciel",
    "kolega",
    "babcia",
    "dziadek",
    "siostra",
    "brat",
    "ciocia",
    "wujek",
    "lekarz",
    "nauczyciel",
    "ptak",
    "koń",
    "krowa",
    "świnia",
    "ryba",
    "mysz",
    # Abstract/Functional
    "imię",
    "nazwisko",
    "wiek",
    "adres",
    "numer",
    "kolor",
    "kształt",
    "część",
    "całość",
    "początek",
    "koniec",
    "błąd",
    "prawda",
    "kłamstwo",
    "pytanie",
    "odpowiedź",
    "zdjęcie",
    "muzyka",
    "film",
    # Prepositions/Other
    "między",
    "obok",
    "przed",
    "za",
    "razem",
    "osobno",
    "tylko",
    "nawet",
    "też",
    "chyba",
    "pewnie",
    "może",
    "naprawdę",
    "właśnie",
]

# Create final list
final_list = []
existing_words = set()

# Add Super Core first
for word, cat, prio in aac_super_core:
    if word not in existing_words:
        final_list.append(
            {
                "word": word,
                "category": cat,
                "priority": prio,
                "source": "AAC_Super_Core",
            }
        )
        existing_words.add(word)

# Add Supplementary
for word in supplementary_raw:
    if word not in existing_words:
        # Simple heuristic for category based on ending (not perfect but helpful)
        cat = "general"
        if word.endswith("ć") or word.endswith("c"):
            cat = "verb"
        elif word.endswith("y") or word.endswith("i"):
            cat = "adjective"

        final_list.append(
            {"word": word, "category": cat, "priority": 3, "source": "High_Frequency"}
        )
        existing_words.add(word)

# Fill up to 500 if needed (simple placeholder logic if short, but list above is approx 300+)
# Let's add some more high freq fillers to ensure we hit 500.
# I'll add a block of common Polish nouns/verbs that are suitable for AAC.

extra_fillers = [
    "śnić",
    "marzyć",
    "planować",
    "kroić",
    "smarować",
    "trzeć",
    "mieszać",
    "piec",
    "smażyć",
    "lać",
    "sypać",
    "odkurzać",
    "zamiatać",
    "myć",
    "wycierać",
    "suszyć",
    "wieszać",
    "składać",
    "ubierać",
    "rozbierać",
    "zapinać",
    "odpinać",
    "wiązać",
    "czesać",
    "ciąć",
    "kleić",
    "pisać",
    "czytać",
    "liczyć",
    "rysować",
    "śpiewać",
    "tańczyć",
    "grać",
    "wygrać",
    "przegrać",
    "dzielić",
    "łączyć",
    "włączać",
    "wyłączać",
    "zepsuć",
    "naprawić",
    "czekać",
    "spieszyć się",
    "odpoczywać",
    "spacerować",
    "podróżować",
    "zwiedzać",
    "pakować",
    "tata",
    "mama",
    "babcia",
    "dziadek",
    "wujek",
    "ciocia",
    "siostra",
    "brat",
    "syn",
    "córka",
    "wnuk",
    "wnuczka",
    "kuzyn",
    "kuzynka",
    "sąsiad",
    "sąsiadka",
    "kolega",
    "koleżanka",
    "przyjaciel",
    "przyjaciółka",
    "wróg",
    "obcy",
    "gość",
    "gospodarz",
    "szef",
    "pracownik",
    "klient",
    "sprzedawca",
    "listonosz",
    "policjant",
    "strażak",
    "lekarz",
    "pielęgniarka",
    "kierowca",
    "kucharz",
    "aktor",
    "piosenkarz",
    "sportowiec",
    "uczeń",
    "student",
    "nauczyciel",
    "kot",
    "pies",
    "chomik",
    "papuga",
    "rybka",
    "królik",
    "mysz",
    "szczur",
    "koń",
    "krowa",
    "świnia",
    "kura",
    "kaczka",
    "gęś",
    "indyk",
    "owca",
    "koza",
    "osioł",
    "lew",
    "tygrys",
    "słoń",
    "żyrafa",
    "małpa",
    "miś",
    "wilk",
    "lis",
    "zając",
    "wiewiórka",
    "jeż",
    "sarna",
    "jeleń",
    "dzik",
    "ptak",
    "gołąb",
    "wróbel",
    "wrona",
    "sroka",
    "orzeł",
    "sowa",
    "bocian",
    "drzewo",
    "krzew",
    "kwiat",
    "trawa",
    "liść",
    "gałąź",
    "pień",
    "korzeń",
    "owoc",
    "jabłko",
    "gruszka",
    "śliwka",
    "wiśnia",
    "czereśnia",
    "truskawka",
    "malina",
    "jagoda",
    "poziomka",
    "banan",
    "pomarańcza",
    "mandarynka",
    "cytryna",
    "grejpfrut",
    "winogrono",
    "arbuz",
    "melon",
    "ananas",
    "kiwi",
    "warzywo",
    "ziemniak",
    "marchew",
    "pietruszka",
    "seler",
    "por",
    "cebula",
    "czosnek",
    "pomidor",
    "ogórek",
    "papryka",
    "sałata",
    "kapusta",
    "kalafior",
    "brokuł",
    "fasola",
    "groch",
    "kukurydza",
    "burak",
    "rzodkiewka",
    "dynia",
    "chleb",
    "bułka",
    "rogal",
    "bagietka",
    "tost",
    "kanapka",
    "masło",
    "ser",
    "szynka",
    "kiełbasa",
    "jajko",
    "omlet",
    "jajecznica",
    "płatki",
    "mleko",
    "jogurt",
    "kefir",
    "twaróg",
    "śmietana",
    "lody",
    "deser",
    "ciasto",
    "tort",
    "ciastko",
    "pączek",
    "drożdżówka",
    "baton",
    "czekolada",
    "cukierek",
    "lizak",
    "guma",
    "sok",
    "woda",
    "herbata",
    "kawa",
    "kakao",
    "kompot",
    "napój",
    "cola",
    "piwo",
    "wino",
    "wódka",
    "zupa",
    "rosół",
    "pomidorowa",
    "ogórkowa",
    "grzybowa",
    "jarzynowa",
    "krupnik",
    "żurek",
    "barszcz",
    "kapuśniak",
    "grochówka",
    "fasolowa",
    "drugie",
    "danie",
    "mięso",
    "kotlet",
    "schabowy",
    "mielony",
    "kurczak",
    "udko",
    "pierś",
    "skrzydełko",
    "ryba",
    "filet",
    "paluszki",
    "frytki",
    "ziemniaki",
    "puree",
    "kluski",
    "pierogi",
    "naleśniki",
    "placki",
    "racuchy",
    "ryż",
    "kasza",
    "makaron",
    "sos",
    "sałatka",
    "surówka",
    "deska",
    "nóż",
    "widelec",
    "łyżka",
    "łyżeczka",
    "talerz",
    "miska",
    "kubek",
    "szklanka",
    "kieliszek",
    "butelka",
    "dzbanek",
    "garnek",
    "patelnia",
    "czajnik",
    "cukiernica",
    "solniczka",
    "pieprzniczka",
    "serwetka",
    "obrus",
    "kuchnia",
    "lodówka",
    "zamrażarka",
    "kuchenka",
    "piekarnik",
    "mikrofala",
    "zmywarka",
    "zlew",
    "kran",
    "szafka",
    "szuflada",
    "półka",
    "kosz",
    "blat",
    "stół",
    "krzesło",
    "dom",
    "mieszkanie",
    "blok",
    "wieżowiec",
    "apartament",
    "willa",
    "dwór",
    "zamek",
    "pałac",
    "hotel",
    "motel",
    "schronisko",
    "namiot",
    "przyczepa",
    "pokój",
    "salon",
    "sypialnia",
    "jadalnia",
    "gabinet",
    "hol",
    "przedpokój",
    "korytarz",
    "schody",
    "winda",
    "piętro",
    "parter",
    "piwnica",
    "strych",
    "dach",
    "komin",
    "rynna",
    "balkon",
    "taras",
    "ganek",
    "wejście",
    "wyjście",
    "drzwi",
    "okno",
    "parapet",
    "ściana",
    "sufit",
    "podłoga",
    "dywan",
    "wykładzina",
    "parkiet",
    "panele",
    "płytki",
    "kafelki",
    "fuga",
    "listwa",
    "gniazdko",
    "włącznik",
    "lampa",
    "żyrandol",
    "kinkiet",
    "lampka",
    "żarówka",
    "mebel",
    "szafa",
    "komoda",
    "regał",
    "biurko",
    "stolik",
    "ława",
    "fotel",
    "kanapa",
    "sofa",
    "wersalka",
    "łóżko",
    "materac",
    "pościel",
    "kołdra",
    "poduszka",
    "prześcieradło",
    "koc",
    "narzuta",
    "zasłona",
    "firanka",
    "roleta",
    "żaluzja",
    "obraz",
    "plakat",
    "zdjęcie",
    "ramka",
    "wazon",
    "doniczka",
    "kwiat",
    "świeca",
    "świecznik",
    "zegar",
    "budzik",
    "lustro",
    "wieszak",
    "stojak",
    "parasol",
    "klucz",
    "breloczek",
    "zamek",
    "klamka",
    "dzwonek",
    "wizjer",
    "wycieraczka",
    "skrzynka",
    "numer",
    "adres",
    "ulica",
    "aleja",
    "plac",
    "skwer",
    "rondo",
    "skrzyżowanie",
    "chodnik",
    "krawężnik",
    "jezdnia",
    "pas",
    "rów",
    "pobocze",
    "droga",
    "szosa",
    "autostrada",
    "ekspresówka",
    "obwodnica",
    "most",
    "wiadukt",
    "tunel",
    "przejście",
    "przejazd",
    "tor",
    "szyna",
    "peron",
    "dworzec",
    "stacja",
    "przystanek",
    "zatoka",
    "bilet",
    "kasownik",
    "rozkład",
    "tablica",
    "informacja",
    "kasa",
    "poczekalnia",
    "bagaż",
    "walizka",
    "torba",
    "plecak",
    "reklamówka",
    "siatka",
    "wózek",
    "koszyk",
    "pieniądz",
    "moneta",
    "banknot",
    "złoty",
    "grosz",
    "karta",
    "portfel",
    "bankomat",
    "bank",
    "poczta",
    "sklep",
    "market",
    "kiosk",
    "stragan",
    "targ",
    "rynek",
    "centrum",
    "galeria",
    "apteka",
    "szpital",
    "przychodnia",
    "gabinet",
    "szkoła",
    "przedszkole",
    "żłobek",
    "uniwersytet",
    "biblioteka",
    "kino",
    "teatr",
    "opera",
    "muzeum",
    "galeria",
    "wystawa",
    "cyrk",
    "zoo",
    "basen",
    "stadion",
    "boisko",
    "kort",
    "lodowisko",
    "siłownia",
    "klub",
    "dyskoteka",
    "bar",
    "pub",
    "kawiarnia",
    "restauracja",
    "pizzeria",
    "hotel",
    "park",
    "las",
    "łąka",
    "pole",
    "góra",
    "morze",
    "jezioro",
    "rzeka",
    "staw",
    "strumyk",
    "plaża",
    "piasek",
    "wydma",
    "klif",
    "skała",
    "kamień",
    "ziemia",
    "błoto",
    "kurz",
    "pył",
    "dym",
    "mgła",
    "chmura",
    "deszcz",
    "śnieg",
    "grad",
    "mróz",
    "lód",
    "szron",
    "wiatr",
    "wichura",
    "burza",
    "piorun",
    "błyskawica",
    "grzmot",
    "tęcza",
    "słońce",
    "księżyc",
    "gwiazda",
    "niebo",
    "kosmos",
    "świat",
    "kraj",
    "państwo",
    "ojczyzna",
    "zagranica",
    "kontynent",
    "wyspa",
]

for word in extra_fillers:
    if word not in existing_words and len(final_list) < 500:
        # Rough categorization for fillers
        cat = "general"
        if word.endswith("ć") or word.endswith("c"):
            cat = "verb"
        elif word[0].isupper():
            cat = "noun"  # Rough check but words are lowercase here
        else:
            cat = "noun"  # Most fillers are nouns

        final_list.append(
            {"word": word, "category": cat, "priority": 4, "source": "Supplementary"}
        )
        existing_words.add(word)

# Write to CSV
with open("core_words_pl.csv", "w", newline="", encoding="utf-8") as f:
    writer = csv.DictWriter(
        f, fieldnames=["rank", "word", "category", "priority", "source"]
    )
    writer.writeheader()
    for i, item in enumerate(final_list):
        writer.writerow(
            {
                "rank": i + 1,
                "word": item["word"],
                "category": item["category"],
                "priority": item["priority"],
                "source": item["source"],
            }
        )

print(f"Generated {len(final_list)} words in core_words_pl.csv")
